Oauth
elemoser/elsparkcyklar-app pull request #35
Opened 2023-12-13 09:15 UTC by elstarkov

Oauth 2.0 implemented in backend. Hopefully it will work for frontend as well

2023-12-14 08:01 UTC, Ylih requested changes
Not working he he

2023-12-16 16:01 UTC, Ylih submitted a review, later dismissed
Well... My code so I think I've reviewed it enough

2023-12-17 10:32 UTC, elemoser reviewed
Allt verkar fungera som tidigare. Även simuleringen fungerar fortfarande. Autentiseringen  fungerar för alla sidor i klientvyn, men admin- och simuleringsvyn är fortfarande tillgängliga utan inloggning. Detta är ok för nu. Det är kanske ännu bättre om simuleringen är tillgänglig utan inloggning. Och för admin-sidan kan ni visa mig hur man gör det senare. 

Ett bekymmer jag har innan mergning gäller sessionDB. 
Vad är sessionDB och bör vi verkligen ladda upp den på vår repo?

2023-12-17 11:10 UTC, elemoser approved these changes
ok!

2023-12-17 19:03 UTC, merged